project:
  type: website
  render: 
    - "*.qmd"
    - "!sphinx/"

jupyter: python3

execute:
  cache: true

website:
  title: "PFJAX"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Quickstart"
        href: pfjax.qmd
      - text: "Tutorials"
        menu:
          - text: "Quickstart"
            href: pfjax.qmd
          - text: "Comparison of Gradient/Hessian Algorithms"
            href: gradient_comparisons.qmd
          - text: "Example: Stochastic Optimization"
            href: stochopt_tutorial.qmd
          - text: "Example: Markov Chain Monte Carlo"
            href: mcmc_tutorial.qmd
      - text: "API Reference"
        href: api/index.qmd
        

format:
  html:
    theme: cosmo

metadata-files:
  - api/_sidebar.yml

bibliography: biblio.bib
citeproc: true

quartodoc:
  package: pfjax
  dir: api
  sidebar: "api/_sidebar.yml"

  sections:
    - title: pfjax
      contents:
        - models.base_model
##        - pfjax.models.bm_model
## - pfjax.models.lotvol_model
##        - models.base_model
##        - pfjax.models.pgnet_model
