project:
  output-dir: _output
  render:
    - "*.qmd"
    - "!/internal/"
    - "!/quarto/"
    - "!/sphinx/"
  resources:
    - hooks
    - javascripts
    - _macros.tex
    - references.bib

jupyter: python3

format:
  mkdocs-gfm:
    shift-heading-level-by: 1

# filters:
#   - _extensions/mkdocs/filters/mklog.lua
